### PR TITLE
Framework v2 compatibility

### PR DESCRIPTION
**Pull request by dancgray**

### CODE REVIEW

**Comment by dancgray** [comment]
@RobertPeek I've added _nthChild to the model could you test again. Thnx

**Comment by RobertPeek** [comment]
No errors are being logged now _nthChild has been set however this hasn't affected the layout issues:

1 - each 'menu-item-indicator' seems to have a 100% width instead of 33% (100/number of items).
2 - 'menu-item-inner' has a margin-right of 2%, which is causing the element to be off center.

**Comment by dancgray** [comment]
The margin-right: 2% is coming from the bomenu.less file in the theme for the kitchen sink course that you are testing in:

	.menu-item {
		margin: 0 auto 30px;

		&.nth-child-even{
			.menu-item-inner{
				margin-left:2%;
		        .dir-rtl & {
		            margin-right:2%;
		        }
			}
		}

		&.nth-child-odd {
			.menu-item-inner {
				margin-right:2%;
                .dir-rtl & {
                    margin-left:2%;
                }
			}
		}
	}

**Comment by dancgray** [comment]
@RobertPeek can you test again and +1 if OK.

**Comment by RobertPeek** [comment]
I have tested in the kitchen sink and by removing the boxMenu.less from the theme it has worked fine.

+1

**Pull request merged**
